### ISSUE TITLE
Anytype

### ISSUE THREAD

**Issue by cyrillebesson** [junaid33/opensource.builders#451] opened 2022-04-22 13:23 UTC
open source and encrypted Notion alternative

website : https://anytype.io/en
twitter : https://twitter.com/anytypelabs?lang=en

**Comment by jcklpe** [comment] 2022-04-22 21:29
Hey thank you for contributing but I have to close this as a dupe of: #99   
Also wrong format. I'll copy over the info to the other ticket. Have a nice day!

**Closed by jcklpe** 2022-04-22 21:29 UTC
