### ISSUE TITLE
LibreOffice Online / Collabora Online

### ISSUE THREAD

**Issue by wget** [junaid33/opensource.builders#223] opened 2020-03-26 11:16 UTC
Office suite in a browser, an alternative to GDocs/MS Office Online.

https://www.collaboraoffice.com/code/

**Comment by jcklpe** [comment] 2020-04-06 18:51
closing as duplicate of : https://github.com/junaid33/opensource.builders/issues/63

**Closed by jcklpe** 2020-04-06 18:51 UTC
