### ISSUE TITLE
ERPNext- Cloud, Open Source Alternative to Proprietary ERP

### ISSUE THREAD

**Issue by jaichavan** [junaid33/opensource.builders#54] opened 2020-02-29 10:12 UTC
ERPNext is a cloud, open source ERP that has been adopted by more than 5000 businesses in the world. Because of its underlying powerful framework, you can create your own version on ERP. One click easy install script, no vendor lock-in, full freedom, and a community of more than 10000 members.
Check out our website [here](https://erpnext.com) 
Our [GitHub Repository](https://github.com/frappe/erpnext)

**Comment by jcklpe** [comment] 2020-04-06 16:50
@jaichavan  Hi, sorry, the closed source project should be in the title of the ticket, and the comments should provide open source alternatives. You have it backwards. Please edit to follow the form correctly.

**Comment by jcklpe** [comment] 2020-04-06 17:13
Actually closing this as a duplicate of https://github.com/junaid33/opensource.builders/issues/77

This was posted the same day as the other project, but this one is invalidly formatted and has less information.

**Closed by jcklpe** 2020-04-06 17:13 UTC
Labels: invalid
