### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by bilalghalib** [junaid33/opensource.builders#215] opened 2020-03-22 22:23 UTC
video conferencing with breakout rooms

**Comment by binc0** [comment] 2020-03-22 22:56
https://jitsi.org

**Comment by jcklpe** [comment] 2020-03-25 03:40
Can second Jitsi. Also worth checking out bigbluebutton and NextCloud Talk.

**Comment by jcklpe** [comment] 2020-03-25 04:29
Duplicate of: https://github.com/junaid33/opensource.builders/issues/157

**Comment by jcklpe** [comment] 2020-04-06 17:51
Closing as duplicate: https://github.com/junaid33/opensource.builders/issues/157

**Closed by jcklpe** 2020-04-06 17:51 UTC
