### ISSUE TITLE
BigBlueButton

### ISSUE THREAD

**Issue by ludwigbald** [junaid33/opensource.builders#266] opened 2020-05-05 08:08 UTC
Video Conferencing/Teaching platform

**Comment by TKaluza** [comment] 2020-05-05 13:19
Alternative too Zoom

**Comment by jcklpe** [comment] 2020-05-05 21:33
incorrect format and also a dupe of: https://github.com/junaid33/opensource.builders/issues/56

closing

**Closed by jcklpe** 2020-05-05 21:33 UTC
