### ISSUE TITLE
JCards

### ISSUE THREAD

**Issue by jcardstimesheetapp** [junaid33/opensource.builders#474] opened 2023-01-20 09:50 UTC
JCards [Time tracking software](https://jcards.com.au/) is a free tool that allows users to track and manage their time spent on various projects or tasks. It can be used for personal or team time management and can help users to improve their productivity and efficiency. The software typically includes features such as task or project tracking, time logging, and reporting capabilities. It may also include integration with other tools such as calendars, invoicing software, or project management platforms. It can be accessed through web browser or mobile app and can be used to track time on desktop or mobile devices.

**Comment by jcklpe** [comment] 2023-02-01 02:49
Closing as dupe of: https://github.com/junaid33/opensource.builders/issues/349

**Closed by jcklpe** 2023-02-01 02:49 UTC
