### ISSUE TITLE
Photoshop

### ISSUE THREAD

**Issue by kush-daga** [junaid33/opensource.builders#191] opened 2020-03-08 15:59 UTC
Photo editing application

**Comment by jcklpe** [comment] 2020-03-25 03:43
Sadly there isn't really a great open source alternative for this. The most direct analog is GIMP which hasn't really improved it's UI or features in like a decade. 

There's a recent offshoot/rebranding of GIMP called Glympse which seems promising. 

And Krita is almost feature par with photoshop if you're just doing digital painting.

**Comment by jcklpe** [comment] 2020-04-06 22:22
Closed as duplicate of: https://github.com/junaid33/opensource.builders/issues/112

**Closed by jcklpe** 2020-04-06 22:22 UTC
