### ISSUE TITLE
Redmine (Alternative to Asana, JIRA)

### ISSUE THREAD

**Issue by yassan** [junaid33/opensource.builders#193] opened 2020-03-09 22:21 UTC
## Category

Project management web application

## OSS alternatives

Asana, JIRA

## Stars

3.7k

## Web Site

https://redmine.org/

## Language

Ruby

## Repository

* [Official SVN repository](https://svn.redmine.org/redmine)
* [Mirror of redmine code source](https://github.com/redmine/redmine)

## Deploy

https://redmine.org/projects/redmine/wiki/Guide

## SVG

http://www.redmine.org/attachments/3462/redmine_fluid_icon.png

(cf. https://www.redmine.org/projects/redmine/wiki/Logo)

## Licence

GPL v2

**Comment by alexanderadam** [comment] 2020-03-10 07:48
Good point! I forgot about it's origins when I created the issue for [OpenProject](https://github.com/junaid33/opensource.builders/issues/70).

**Comment by jcklpe** [comment] 2020-04-06 22:18
Closed as duplicate of https://github.com/junaid33/opensource.builders/issues/70

**Closed by jcklpe** 2020-04-06 22:18 UTC
