### ISSUE TITLE
Pipedrive

### ISSUE THREAD

**Issue by gEndelf** [junaid33/opensource.builders#89] opened 2020-02-29 18:38 UTC
CRM for sales

**Comment by mjjzf** [comment] 2020-03-18 10:07
[Vtiger](http://vtiger.com) and [SugarCRM](http://sugarcrm.com) are both open source.
They both have mobile clients, too.

**Comment by mjjzf** [comment] 2020-03-18 10:55
Merge with #82 ?

**Comment by gEndelf** [comment] 2020-03-21 20:00
@mjjzf SugarCRM completed support CE version

**Comment by jcklpe** [comment] 2020-03-22 21:44
I've also read about Odoo as a CRM alternative but don't know much about it as I've never used it myself.

**Comment by jcklpe** [comment] 2020-04-06 17:22
I'm not clear on the differences between CRMs and ERPs but this appears to be a duplicate of https://github.com/junaid33/opensource.builders/issues/77

@gEndelf please merge if appropriate.

**Closed** 2020-04-09 08:02 UTC
Labels: request
