### ISSUE TITLE
Dolibarr ERP CRM

### ISSUE THREAD

**Issue by eldy** [junaid33/opensource.builders#328] opened 2020-07-13 21:17 UTC
Open source suite for business (ERP, CRM, MRP...)

Dolibarr ERP CRM is an Open Source alternative to SAP, Netsuite, Odoo, Microsoft Dynamics, Compiere, OpenBravo, Salesforce, SugarCRM, ERPNext, Oracle ERP, Sage, and more.

See https://www.dolibarr.org

**Comment by jcklpe** [comment] 2020-07-16 03:35
@eldy closing as a dupe of #81   
If you'd like you can add the dollibarr info there in the comments.   
  
And for future reference this issue ticket was also not according to the repo format.

**Closed by jcklpe** 2020-07-16 03:35 UTC
