### ISSUE TITLE
Retool

### ISSUE THREAD

**Issue by rorosan** [junaid33/opensource.builders#415] opened 2021-06-15 10:32 UTC
ToolJet is an opensource alternative to retool, a nocode software to enable companies to easily make internal tools.
https://github.com/ToolJet/ToolJet

Thanks !

**Comment by jcklpe** [comment] 2021-06-19 01:40
@rorosan Rad project. I'm closing as dupe of this ticket thoughhttps://github.com/junaid33/opensource.builders/issues/376

**Closed by jcklpe** 2021-06-19 01:40 UTC
