### ISSUE TITLE
Airtable 

### ISSUE THREAD

**Issue by stokebreakup** [junaid33/opensource.builders#515] opened 2024-05-21 23:15 UTC
Airtable is a spreadsheet-database hybrid, with the features of a database but applied to a spreadsheet. 

*alternatives, open source*
baserow (https://github.com/bram2w/baserow)
nocodb (https://github.com/nocodb/nocodb)
CsvTextEditor (https://github.com/WildGums/CsvTextEditor)
csveditor (https://github.com/ssebs/csveditor)
comma chameleon (https://github.com/theodi/comma-chameleon)
sqlitebrowser(https://github.com/sqlitebrowser/sqlitebrowser)
postgui(https://github.com/priyank-purohit/PostGUI)
sqlite-gui(https://github.com/little-brother/sqlite-gui)
antares (https://github.com/antares-sql/antares)
pg (https://github.com/datawan-labs/pg)
pgweb(https://github.com/sosedoff/pgweb)
phpmyadmin (https://github.com/phpmyadmin/phpmyadmin)
TableTool(https://github.com/jakob/TableTool)
CSVAnalyzerPro(https://github.com/CoderJoeW/CSVAnalyzerPro)
table-magic(https://github.com/stevecat/table-magic)
HeidiSQL(https://github.com/HeidiSQL/HeidiSQL)
usql(https://github.com/xo/usql)
Luckysheet(https://github.com/dream-num/Luckysheet)
beekeeper-studio(https://github.com/beekeeper-studio/beekeeper-studio)

**Comment by jcklpe** [comment] 2024-06-12 23:39
Fantastic contribution but I'm closing as a dupe of: #214   
  
Thank you!

**Closed by jcklpe** 2024-06-12 23:39 UTC
