### ISSUE TITLE
Zoho

### ISSUE THREAD

**Issue by jitenagarwal19** [junaid33/opensource.builders#81] opened 2020-02-29 15:45 UTC
ERP Solutions

**Comment by spannella** [comment] 2020-03-03 20:21
Zoho’s email client / contacts management would be awesome

**Comment by jewelhuq** [comment] 2020-03-05 02:29
Zoho Subscription, Books

**Comment by jcklpe** [comment] 2020-04-06 17:14
@jitenagarwal19 , @spannella , @jewelhuq 

Is this a duplicate of: https://github.com/junaid33/opensource.builders/issues/77

I don't use Zoho, and I'm not super familiar with the ERP space.

**Comment by jcklpe** [comment] 2020-07-16 03:37
Closing this as dupe for #77

**Closed by jcklpe** 2020-07-16 03:37 UTC
Labels: request
