### ISSUE TITLE
Odoo

### ISSUE THREAD

**Issue by ryanc-me** [junaid33/opensource.builders#51] opened 2020-02-29 05:35 UTC
ERP Platform. POS, Accounting, eCommerce, Inventory, etc.

**Comment by junaid33** [comment] 2020-02-29 20:36
What commercial software is Odoo an alternative to?

**Comment by ryanc-me** [comment] 2020-02-29 23:22
It's a little difficult to compare directly, because Odoo has first-class apps for such a wide range of business functions (a bit of backup on that claim [here](https://www.odoo.com/page/all-apps)).

The main competition would be other ERP applications like SAP, Salesforce, etc.

Here are a few (admittedly unbiased) articles:
- [Odoo vs Salesforce](https://www.odoo.com/page/compare-odoo-vs-salesforce)
- [Odoo vs SAP](https://www.odoo.com/page/compare-odoo-vs-sap)
- [Odoo vs Sage](https://www.odoo.com/page/compare-odoo-vs-sage)
- [Odoo vs Xero (Accounting)](https://www.odoo.com/page/compare-odoo-vs-xero)


Would it be acceptable to have Odoo listed as an alternative to multiple pieces of commercial software?

**Comment by jcklpe** [comment] 2020-04-06 16:48
@ryanc-me Hi, sorry, the closed source project should be in the title of the ticket, and the comments should provide open source alternatives. You have it backwards. Please edit to follow the form correctly.

**Comment by jcklpe** [comment] 2020-04-06 17:12
Actually closing this as a duplicate of https://github.com/junaid33/opensource.builders/issues/77

This was posted first, but the second ticket was correctly formatted and has multiple alternatives.

**Closed by jcklpe** 2020-04-06 17:12 UTC
Labels: invalid
