### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by dvassallo** [junaid33/opensource.builders#177] opened 2020-03-06 02:05 UTC
Web application development platform

**Comment by jcklpe** [comment] 2020-03-25 04:33
duplicate of https://github.com/junaid33/opensource.builders/issues/50

**Comment by jcklpe** [comment] 2020-04-06 16:46
Closing as duplicate. Please be sure to check if requests have already been made. Thank you!

**Closed by jcklpe** 2020-04-06 16:46 UTC
