### ISSUE TITLE
Retool / Outsystems / Mendix

### ISSUE THREAD

**Issue by joebudi** [junaid33/opensource.builders#376] opened 2021-01-22 10:35 UTC
Budibase - https://github.com/Budibase/budibase

**Comment by jcklpe** [comment] 2021-01-23 20:22
@joebudi : wrong format. Please put the open source project in the comments and the closed source which it is an alternative to in the title. Also please provide links. It's basically impossible to google "retool opensource". Marking invalid. If not corrected within 30 days I'll close the ticket.

**Comment by joebudi** [comment] 2021-01-23 20:40
Is that ok?

**Comment by jcklpe** [comment] 2021-01-26 01:33
@joebudi Is  the closed source project called Retool? Sorry I wasn't familar and assumed that was the open source project.

**Comment by jcklpe** [comment] 2021-01-26 01:35
@joebudi Would budibase be comparable to something like Framer X or webflow? It looks like it's a GUI based application for making applications?

**Comment by joebudi** [comment] 2021-01-26 08:55
@jcklpe Retool is closed. Budibase is open source.
Budibase is like Webflow, but for building web applications/internal tools/crud apps. It's an alternative to closed source projects such as Retool, Outsystems, Mendix.

**Comment by jcklpe** [comment] 2021-01-29 04:23
@joebudi Oh dope, now I get. I actually just saw someone post budibase to reddit! Very cool looking project! Thank you for contributing.

**Comment by jcklpe** [comment] 2021-05-25 22:39
Apologies, I just realized that this is a dupe of: https://github.com/junaid33/opensource.builders/issues/290

Closing as dupe

**Closed by jcklpe** 2021-05-25 22:39 UTC
Labels: request
