### ISSUE TITLE
New Relic

### ISSUE THREAD

**Issue by NGrPXL** [junaid33/opensource.builders#230] opened 2020-04-02 09:33 UTC
Grafana
https://grafana.com/

**Comment by kortov** [comment] 2020-04-02 10:05
Grafana is OSS itself, isn't it?

**Comment by NGrPXL** [comment] 2020-04-02 10:51
Grafana is the tool to visualize, and they have additional solutions to provide a full OSS (from my understanding) such as Prometheus, Loki, etc...

**Comment by jcklpe** [comment] 2020-04-06 16:43
@NGrPXL  Hi, sorry, the closed source project should be in the title of the ticket, and the comments should provide open source alternatives. You have it backwards. Please edit to follow the form correctly.

**Comment by jcklpe** [comment] 2020-04-06 16:44
Also this may be a duplicate of https://github.com/junaid33/opensource.builders/issues/230

**Comment by jcklpe** [comment] 2020-04-06 22:34
Actually found this is a dupe of https://github.com/junaid33/opensource.builders/issues/170

**Closed** 2020-04-06 22:34 UTC
