### ISSUE TITLE
Harvest

### ISSUE THREAD

**Issue by abogawat** [junaid33/opensource.builders#102] opened 2020-03-01 12:51 UTC
Time tracking platform

**Comment by mjjzf** [comment] 2020-03-18 10:10
I did the translation on [Kimai](https://www.kimai.org/), which does good tracking and reports.
There is a [time tracker app for Nextcloud](https://apps.nextcloud.com/apps/timetracker), but it has not been to reliable, so I went back to my Kimai install.

**Comment by jcklpe** [comment] 2020-04-06 17:27
Closing as duplicate of https://github.com/junaid33/opensource.builders/issues/74

**Closed by jcklpe** 2020-04-06 17:27 UTC
Labels: request
